name: calderum
description: A magical potion brewing board game app inspired by Pócimas y Brebajes.
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  go_router: ^14.0.0
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  supabase_flutter: ^2.0.0
  flutter_dotenv: ^5.1.0
  riverpod_annotation: ^2.6.1
  nanoid: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.15
  freezed: ^3.0.6
  json_serializable: ^6.9.5
  riverpod_generator: ^2.6.4
  custom_lint: ^0.7.3
  riverpod_lint: ^2.6.4
  uuid: ^4.0.0
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - .env
  fonts:
    - family: Caudex
      fonts:
        - asset: assets/fonts/Caudex/Caudex-Regular.ttf
        - asset: assets/fonts/Caudex/Caudex-Bold.ttf
          weight: 700
        - asset: assets/fonts/Caudex/Caudex-Italic.ttf
          style: italic
        - asset: assets/fonts/Caudex/Caudex-BoldItalic.ttf
          weight: 700
          style: italic

    - family: Caveat
      fonts:
        - asset: assets/fonts/Caveat/Caveat-Regular.ttf
        - asset: assets/fonts/Caveat/Caveat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Caveat/Caveat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Caveat/Caveat-Bold.ttf
          weight: 700
