name: calderum
description: A magical potion brewing board game app inspired by Pócimas y Brebajes.
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  go_router: ^14.0.0
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  supabase_flutter: ^2.0.0
  flutter_dotenv: ^5.1.0
  riverpod_annotation: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.15
  freezed: ^3.0.6
  json_serializable: ^6.9.5
  riverpod_generator: ^2.6.4
  custom_lint: ^0.7.3
  riverpod_lint: ^2.6.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/
