// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIUhCX6P_h0eMKu4t0r1XreU4FEovEcVI',
    appId: '1:549073578108:web:700e82917c49c523ebc1f9',
    messagingSenderId: '549073578108',
    projectId: 'calderum-e4703',
    authDomain: 'calderum-e4703.firebaseapp.com',
    storageBucket: 'calderum-e4703.firebasestorage.app',
    measurementId: 'G-W76P56PNKH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzClWqlXtuC0bAVepDy5kBfNi1C23p3nA',
    appId: '1:549073578108:android:cb7a2852b4954937ebc1f9',
    messagingSenderId: '549073578108',
    projectId: 'calderum-e4703',
    storageBucket: 'calderum-e4703.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmjCueXOEmxIV4yvz4uzzKczRZqlJAY6E',
    appId: '1:549073578108:ios:a9e4abb0da3f75afebc1f9',
    messagingSenderId: '549073578108',
    projectId: 'calderum-e4703',
    storageBucket: 'calderum-e4703.firebasestorage.app',
    iosBundleId: 'com.example.calderum',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmjCueXOEmxIV4yvz4uzzKczRZqlJAY6E',
    appId: '1:549073578108:ios:a9e4abb0da3f75afebc1f9',
    messagingSenderId: '549073578108',
    projectId: 'calderum-e4703',
    storageBucket: 'calderum-e4703.firebasestorage.app',
    iosBundleId: 'com.example.calderum',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIUhCX6P_h0eMKu4t0r1XreU4FEovEcVI',
    appId: '1:549073578108:web:8e5d8d8e9758af56ebc1f9',
    messagingSenderId: '549073578108',
    projectId: 'calderum-e4703',
    authDomain: 'calderum-e4703.firebaseapp.com',
    storageBucket: 'calderum-e4703.firebasestorage.app',
    measurementId: 'G-7YHJ4G07CR',
  );
}
